$latex = 'latex --halt-on-error --interaction=nonstopmode %O %S';
$pdflatex = 'pdflatex --halt-on-error --interaction=nonstopmode %O %S';
$lualatex = 'lualatex --halt-on-error --interaction=nonstopmode %O %S';
$xelatex = 'xelatex --no-pdf --halt-on-error --interaction=nonstopmode %O %S';
$makeindex = 'makeindex -s python.ist %O -o %D %S';
add_cus_dep( "glo", "gls", 0, "makeglo" );
sub makeglo {
 return system( "makeindex -s gglo.ist -o '$_[0].gls' '$_[0].glo'" );
}
