from setuptools import find_packages, setup

import sphinx

with open('README.rst', encoding='utf-8') as f:
    long_desc = f.read()

setup(
    name='Sphinx',
    version=sphinx.__version__,
    url='https://www.sphinx-doc.org/',
    download_url='https://pypi.org/project/Sphinx/',
    license='BSD',
    author='Georg Brandl',
    author_email='georg@python.org',
    description='Python documentation generator',
    long_description=long_desc,
    long_description_content_type='text/x-rst',
    project_urls={
        "Code": "https://github.com/sphinx-doc/sphinx",
        "Changelog": "https://www.sphinx-doc.org/en/master/changes.html",
        "Issue tracker": "https://github.com/sphinx-doc/sphinx/issues",
    },
    zip_safe=False,
    classifiers=[
        'Development Status :: 5 - Production/Stable',
        'Environment :: Console',
        'Environment :: Web Environment',
        'Intended Audience :: Developers',
        'Intended Audience :: Education',
        'Intended Audience :: End Users/Desktop',
        'Intended Audience :: Science/Research',
        'Intended Audience :: System Administrators',
        'License :: OSI Approved :: BSD License',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Programming Language :: Python :: 3',
        'Programming Language :: Python :: 3 :: Only',
        'Programming Language :: Python :: 3.6',
        'Programming Language :: Python :: 3.7',
        'Programming Language :: Python :: 3.8',
        'Programming Language :: Python :: 3.9',
        'Programming Language :: Python :: 3.10',
        'Programming Language :: Python :: Implementation :: CPython',
        'Programming Language :: Python :: Implementation :: PyPy',
        'Framework :: Setuptools Plugin',
        'Framework :: Sphinx',
        'Framework :: Sphinx :: Extension',
        'Framework :: Sphinx :: Theme',
        'Topic :: Documentation',
        'Topic :: Documentation :: Sphinx',
        'Topic :: Internet :: WWW/HTTP :: Site Management',
        'Topic :: Printing',
        'Topic :: Software Development',
        'Topic :: Software Development :: Documentation',
        'Topic :: Text Processing',
        'Topic :: Text Processing :: General',
        'Topic :: Text Processing :: Indexing',
        'Topic :: Text Processing :: Markup',
        'Topic :: Text Processing :: Markup :: HTML',
        'Topic :: Text Processing :: Markup :: LaTeX',
        'Topic :: Utilities',
    ],
    platforms='any',
    packages=find_packages(exclude=['tests', 'utils']),
    package_data = {
        'sphinx': ['py.typed'],
    },
    include_package_data=True,
    entry_points={
        'console_scripts': [
            'sphinx-build = sphinx.cmd.build:main',
            'sphinx-quickstart = sphinx.cmd.quickstart:main',
            'sphinx-apidoc = sphinx.ext.apidoc:main',
            'sphinx-autogen = sphinx.ext.autosummary.generate:main',
        ],
        'distutils.commands': [
            'build_sphinx = sphinx.setup_command:BuildDoc',
        ],
    },
    python_requires=">=3.6",
    install_requires=[
        'sphinxcontrib-applehelp',
        'sphinxcontrib-devhelp',
        'sphinxcontrib-jsmath',
        'sphinxcontrib-htmlhelp>=2.0.0',
        'sphinxcontrib-serializinghtml>=1.1.5',
        'sphinxcontrib-qthelp',
        'Jinja2>=3.0',
        'Pygments>=2.12',
        'docutils>=0.14,<0.20',
        'snowballstemmer>=2.0',
        'babel>=2.9',
        'alabaster>=0.7,<0.8',
        'imagesize>=1.3',
        'requests>=2.5.0',
        'packaging>=21.0',
        "importlib-metadata>=4.8; python_version < '3.10'",
        "colorama>=0.4.5; sys_platform == 'win32'",
    ],
    extras_require={
        'docs': [
            'sphinxcontrib-websupport',
        ],
        'lint': [
            'flake8>=3.5.0',
            'flake8-comprehensions',
            'flake8-bugbear',
            'isort',
            'mypy>=0.971',
            'sphinx-lint',
            'docutils-stubs',
            "types-typed-ast",
            "types-requests",
        ],
        'test': [
            'pytest>=4.6',
            'html5lib',
            "typed_ast; python_version < '3.8'",
            'cython',
        ],
    },
)
