"""To publish HTML docs at GitHub Pages, create .nojekyll file."""

from __future__ import annotations

import urllib
from pathlib import Path
from typing import Any

import sphinx
from sphinx.application import Sphinx
from sphinx.environment import BuildEnvironment


def create_nojekyll_and_cname(app: Sphinx, env: BuildEnvironment) -> None:
    if app.builder.format == 'html':
        (Path(app.builder.outdir) / '.nojekyll').touch()

        html_baseurl = app.config.html_baseurl
        cname_path = Path(app.builder.outdir) / 'CNAME'
        domain = urllib.parse.urlparse(html_baseurl).hostname if html_baseurl else None
        if domain and not domain.endswith(".github.io"):
            with cname_path.open('w', encoding="utf-8") as f:
                # NOTE: don't write a trailing newline. The `CNAME` file that's
                # auto-generated by the Github UI doesn't have one.
                f.write(domain)
        else:
            cname_path.unlink(missing_ok=True)


def setup(app: Sphinx) -> dict[str, Any]:
    app.connect('env-updated', create_nojekyll_and_cname)
    return {'version': sphinx.__display_version__, 'parallel_read_safe': True}
