.TH sphinx-quickstart 1 "Jan 2009" "Sphinx 0.6" "User Commands"
.SH NAME
sphinx-quickstart \- Sphinx documentation template generator
.SH SYNOPSIS
.B sphinx-quickstart
.SH DESCRIPTION
sphinx-quickstart is an interactive tool that asks some questions about your
project and then generates a complete documentation directory and sample
Makefile to be used with \fBsphinx-build(1)\fR.
.SH "SEE ALSO"
.BR sphinx-build(1)
.SH AUTHOR
Georg Brandl <georg@python.org>, Armin Ronacher <armin.ronacher@active-4.com> et
al.
.PP
This manual page was initially written by Mikhail Gusarov
<dottedmag@dottedmag.net> for the Debian project.
