from __future__ import annotations

# Global configuration constants for Sphinx application

builtin_extensions: tuple[str, ...] = (
    'sphinx.addnodes',
    'sphinx.builders.changes',
    'sphinx.builders.epub3',
    'sphinx.builders.dirhtml',
    'sphinx.builders.dummy',
    'sphinx.builders.gettext',
    'sphinx.builders.html',
    'sphinx.builders.latex',
    'sphinx.builders.linkcheck',
    'sphinx.builders.manpage',
    'sphinx.builders.singlehtml',
    'sphinx.builders.texinfo',
    'sphinx.builders.text',
    'sphinx.builders.xml',
    'sphinx.config',
    'sphinx.domains.c',
    'sphinx.domains.changeset',
    'sphinx.domains.citation',
    'sphinx.domains.cpp',
    'sphinx.domains.index',
    'sphinx.domains.javascript',
    'sphinx.domains.math',
    'sphinx.domains.python',
    'sphinx.domains.rst',
    'sphinx.domains.std',
    'sphinx.directives',
    'sphinx.directives.admonitions',
    'sphinx.directives.code',
    'sphinx.directives.cpp',
    'sphinx.directives.misc',
    'sphinx.directives.needs_sphinx',
    'sphinx.directives.other',
    'sphinx.directives.patches',
    'sphinx.environment',
    'sphinx.environment.collectors.asset',
    'sphinx.environment.collectors.dependency',
    'sphinx.environment.collectors.metadata',
    'sphinx.environment.collectors.title',
    'sphinx.ext.autodoc',
    'sphinx.ext.autodoc.typehints',
    'sphinx.ext.autosummary',
    'sphinx.ext.doctest',
    'sphinx.ext.duration',
    'sphinx.ext.extlinks',
    'sphinx.ext.githubpages',
    'sphinx.ext.graphviz',
    'sphinx.ext.ifconfig',
    'sphinx.ext.imgconverter',
    'sphinx.ext.imgmath',
    'sphinx.ext.inheritance_diagram',
    'sphinx.ext.intersphinx',
    'sphinx.ext.linkcode',
    'sphinx.ext.mathjax',
    'sphinx.ext.napoleon',
    'sphinx.ext.todo',
    'sphinx.ext.viewcode',
    'sphinx.parsers.rst',
    'sphinx.parsers.rst.directives',
    'sphinx.parsers.rst.roles',
    'sphinx.roles',
    'sphinx.transforms',
    'sphinx.transforms.i18n',
    'sphinx.transforms.post_transforms',
    'sphinx.transforms.post_transforms.code',
    'sphinx.transforms.post_transforms.images',
    'sphinx.transforms.pre_transforms',
    'sphinx.writers',
    'sphinx.writers.html',
    'sphinx.writers.html5',
    'sphinx.writers.latex',
    'sphinx.writers.manpage',
    'sphinx.writers.texinfo',
    'sphinx.writers.text',
)

# Define __all__ for this module
__all__ = ['builtin_extensions']
