"""Single HTML builders."""

from __future__ import annotations

import base64
import html
import re
import warnings
from pathlib import Path
from typing import TYPE_CHECKING
from urllib.parse import unquote, urlsplit

from docutils import nodes

from sphinx._cli.util.colour import darkgreen
from sphinx.builders.html import StandaloneHTMLBuilder
from sphinx.deprecation import RemovedInSphinx10Warning
from sphinx.environment.adapters.toctree import global_toctree_for_doc
from sphinx.locale import __
from sphinx.util import logging
from sphinx.util.display import progress_message
from sphinx.util.images import guess_mimetype
from sphinx.util.nodes import inline_all_toctrees

if TYPE_CHECKING:
    from collections.abc import Set
    from typing import Any

    from docutils.nodes import Node

    from sphinx.application import Sphinx
    from sphinx.util.typing import ExtensionMetadata

logger = logging.getLogger(__name__)


class SingleFileHTMLBuilder(StandaloneHTMLBuilder):
    """Builds the whole document tree as a single HTML page."""

    name = 'singlehtml'
    epilog = __('The HTML page is in %(outdir)s.')

    copysource = False

    def get_outdated_docs(self) -> str | list[str]:  # type: ignore[override]
        return 'all documents'

    def get_target_uri(self, docname: str, typ: str | None = None) -> str:
        if docname in self.env.all_docs:
            # all references are on the same page...
            return '#document-' + docname
        else:
            # chances are this is a html_additional_page
            return docname + self.out_suffix

    def get_relative_uri(self, from_: str, to: str, typ: str | None = None) -> str:
        # ignore source
        return self.get_target_uri(to, typ)

    def fix_refuris(self, tree: Node) -> None:
        deprecation_msg = (
            "The 'SingleFileHTMLBuilder.fix_refuris' method is no longer used "
            'within the builder and is planned for removal in Sphinx 10. '
            'Please report malformed URIs generated by the Sphinx singlehtml '
            'builder as bugreports.'
        )
        warnings.warn(deprecation_msg, RemovedInSphinx10Warning, stacklevel=2)

        # fix refuris with double anchor
        for refnode in tree.findall(nodes.reference):
            if 'refuri' not in refnode:
                continue
            refuri = refnode['refuri']
            hashindex = refuri.find('#')
            if hashindex < 0:
                continue
            hashindex = refuri.find('#', hashindex + 1)
            if hashindex >= 0:
                # all references are on the same page...
                refnode['refuri'] = refuri[hashindex:]

    def _get_local_toctree(
        self, docname: str, collapse: bool = True, **kwargs: Any
    ) -> str:
        if isinstance(includehidden := kwargs.get('includehidden'), str):
            if includehidden.lower() == 'false':
                kwargs['includehidden'] = False
            elif includehidden.lower() == 'true':
                kwargs['includehidden'] = True
        if kwargs.get('maxdepth') == '':  # NoQA: PLC1901
            kwargs.pop('maxdepth')
        toctree = global_toctree_for_doc(
            self.env, docname, self, tags=self.tags, collapse=collapse, **kwargs
        )
        return self.render_partial(toctree)['fragment']

    def assemble_doctree(self) -> nodes.document:
        master = self.config.root_doc
        tree = self.env.get_doctree(master)
        logger.info(darkgreen(master))
        tree = inline_all_toctrees(self, set(), master, tree, darkgreen, [master])
        tree['docname'] = master
        self.env.resolve_references(tree, master, self)
        return tree

    def assemble_toc_secnumbers(self) -> dict[str, dict[str, tuple[int, ...]]]:
        # Assemble toc_secnumbers to resolve section numbers on SingleHTML.
        # Merge all secnumbers to single secnumber.
        #
        # Note: current Sphinx has refid confliction in singlehtml mode.
        #       To avoid the problem, it replaces key of secnumbers to
        #       tuple of docname and refid.
        #
        #       There are related codes in inline_all_toctres() and
        #       HTMLTranslter#add_secnumber().
        new_secnumbers: dict[str, tuple[int, ...]] = {}
        for docname, secnums in self.env.toc_secnumbers.items():
            for id, secnum in secnums.items():
                alias = f'{docname}/{id}'
                new_secnumbers[alias] = secnum

        return {self.config.root_doc: new_secnumbers}

    def assemble_toc_fignumbers(
        self,
    ) -> dict[str, dict[str, dict[str, tuple[int, ...]]]]:
        # Assemble toc_fignumbers to resolve figure numbers on SingleHTML.
        # Merge all fignumbers to single fignumber.
        #
        # Note: current Sphinx has refid confliction in singlehtml mode.
        #       To avoid the problem, it replaces key of secnumbers to
        #       tuple of docname and refid.
        #
        #       There are related codes in inline_all_toctres() and
        #       HTMLTranslter#add_fignumber().
        new_fignumbers: dict[str, dict[str, tuple[int, ...]]] = {}
        # {'foo': {'figure': {'id2': (2,), 'id1': (1,)}}, 'bar': {'figure': {'id1': (3,)}}}
        for docname, fignumlist in self.env.toc_fignumbers.items():
            for figtype, fignums in fignumlist.items():
                alias = f'{docname}/{figtype}'
                new_fignumbers.setdefault(alias, {})
                for id, fignum in fignums.items():
                    new_fignumbers[alias][id] = fignum

        return {self.config.root_doc: new_fignumbers}

    def get_doc_context(self, docname: str, body: str, metatags: str) -> dict[str, Any]:
        # no relation links...
        toctree = global_toctree_for_doc(
            self.env, self.config.root_doc, self, tags=self.tags, collapse=False
        )
        # if there is no toctree, toc is None
        if toctree:
            toc = self.render_partial(toctree)['fragment']
            display_toc = True
        else:
            toc = ''
            display_toc = False
        return {
            'parents': [],
            'prev': None,
            'next': None,
            'docstitle': None,
            'title': self.config.html_title,
            'meta': None,
            'body': body,
            'metatags': metatags,
            'rellinks': [],
            'sourcename': '',
            'toc': toc,
            'display_toc': display_toc,
        }

    def write_documents(self, _docnames: Set[str]) -> None:
        self.prepare_writing(self.env.all_docs.keys())

        with progress_message(__('assembling single document'), nonl=False):
            doctree = self.assemble_doctree()
            self.env.toc_secnumbers = self.assemble_toc_secnumbers()
            self.env.toc_fignumbers = self.assemble_toc_fignumbers()

        with progress_message(__('writing')):
            self.write_doc_serialized(self.config.root_doc, doctree)
            self.write_doc(self.config.root_doc, doctree)

    def finish(self) -> None:
        self.write_additional_files()
        self.copy_image_files()
        self.copy_download_files()
        self.copy_static_files()
        self.copy_extra_files()
        self.write_buildinfo()
        self.dump_inventory()

    @progress_message(__('writing additional files'))
    def write_additional_files(self) -> None:
        # no indices or search pages are supported

        # additional pages from conf.py
        for pagename, template in self.config.html_additional_pages.items():
            logger.info(' %s', pagename, nonl=True)
            self.handle_page(pagename, {}, template)

        if self.config.html_use_opensearch:
            logger.info(' opensearch', nonl=True)
            self.handle_page(
                'opensearch',
                {},
                'opensearch.xml',
                outfilename=self._static_dir / 'opensearch.xml',
            )


#: Attributes within an HTML start tag (values must be quoted).
_ATTR_RE = re.compile(
    r"""(?P<name>[^\s=<>/]+)\s*=\s*(?P<quote>["'])(?P<value>.*?)(?P=quote)""",
    re.DOTALL,
)
_LINK_TAG_RE = re.compile(r'<link\b[^>]*>', re.IGNORECASE)
_SCRIPT_TAG_RE = re.compile(r'<script\b(?P<attrs>[^>]*)>\s*</script>', re.IGNORECASE)
_IMG_TAG_RE = re.compile(r'<img\b[^>]*>', re.IGNORECASE)
_SCRIPT_CLOSE_RE = re.compile(r'</(script)', re.IGNORECASE)
#: ``url(...)`` tokens in a stylesheet.
_CSS_URL_RE = re.compile(
    r"""url\(\s*(?P<quote>["']?)(?P<url>[^"')]+?)(?P=quote)\s*\)"""
)
#: ``@import "..."`` or ``@import url(...)`` rules without media queries.
_CSS_IMPORT_RE = re.compile(
    r"""@import\s+(?:url\(\s*)?(?P<quote>["']?)(?P<url>[^"'();]+?)(?P=quote)\s*\)?\s*;"""
)


def _tag_attributes(tag: str) -> dict[str, str]:
    """Extract the quoted attributes of a single HTML start tag."""
    return {m['name'].lower(): m['value'] for m in _ATTR_RE.finditer(tag)}


def _replace_attribute_value(tag: str, name: str, new_value: str) -> str:
    """Replace the value of the *name* attribute within an HTML start tag."""
    pattern = re.compile(
        rf"""({re.escape(name)}\s*=\s*)(["']).*?\2""",
        re.DOTALL | re.IGNORECASE,
    )
    return pattern.sub(lambda m: f'{m[1]}{m[2]}{new_value}{m[2]}', tag, count=1)


def _local_asset_path(url: str, base_dir: Path, outdir: Path) -> Path | None:
    """Resolve *url* to an existing file within *outdir*, if it is local.

    Returns ``None`` for external references (e.g. ``https://`` or
    protocol-relative URLs), ``data:`` URIs, fragments,
    and references to files that do not exist within the output directory.
    """
    if not url or url.startswith(('#', '//')):
        return None
    if urlsplit(url).scheme:
        return None
    # remove any query string ('?v=...' checksums) or fragment
    path_part = url.partition('#')[0].partition('?')[0]
    if not path_part:
        return None
    path = (base_dir / unquote(path_part)).resolve()
    if not path.is_relative_to(outdir.resolve()):
        return None
    if not path.is_file():
        return None
    return path


def _data_uri(path: Path) -> str:
    """Encode the file at *path* as a ``data:`` URI."""
    mimetype = guess_mimetype(path, default='application/octet-stream')
    payload = base64.b64encode(path.read_bytes()).decode('ascii')
    return f'data:{mimetype};base64,{payload}'


def _inline_css(path: Path, outdir: Path, _depth: int = 0) -> str | None:
    """Load a stylesheet, inlining local ``@import`` and ``url()`` references.

    Returns ``None`` if the stylesheet cannot be embedded safely.
    """
    if _depth > 10:  # avoid cyclic or pathological @import chains
        return None
    try:
        css = path.read_text(encoding='utf-8')
    except (OSError, UnicodeDecodeError):
        return None
    if '</style' in css.lower():
        # would terminate the enclosing <style> element early
        return None
    base_dir = path.parent

    def replace_import(match: re.Match[str]) -> str:
        target = _local_asset_path(match['url'], base_dir, outdir)
        if target is None or target == path:
            return match[0]
        inlined = _inline_css(target, outdir, _depth + 1)
        if inlined is None:
            return match[0]
        return inlined

    css = _CSS_IMPORT_RE.sub(replace_import, css)

    def replace_url(match: re.Match[str]) -> str:
        target = _local_asset_path(match['url'], base_dir, outdir)
        if target is None:
            return match[0]
        return f'url({_data_uri(target)})'

    return _CSS_URL_RE.sub(replace_url, css)


def _embed_assets_in_page(page_path: Path, outdir: Path) -> None:
    """Rewrite *page_path* so that local assets are embedded into the page.

    Local stylesheets become ``<style>`` elements, local scripts become
    inline ``<script>`` elements, and local images and icons are embedded
    as ``data:`` URIs. External (e.g. ``https://``) references are
    left untouched.
    """
    page = page_path.read_text(encoding='utf-8')
    page_dir = page_path.parent

    def replace_link(match: re.Match[str]) -> str:
        tag = match[0]
        attrs = _tag_attributes(tag)
        rel = attrs.get('rel', '').lower().split()
        href = attrs.get('href', '')
        path = _local_asset_path(href, page_dir, outdir)
        if path is None:
            return tag
        if 'stylesheet' in rel and 'alternate' not in rel:
            css = _inline_css(path, outdir)
            if css is None:
                return tag
            media = attrs.get('media', '')
            media_attr = f' media="{html.escape(media, quote=True)}"' if media else ''
            return f'<style{media_attr}>\n{css}\n</style>'
        if 'icon' in rel or 'apple-touch-icon' in rel:
            return _replace_attribute_value(tag, 'href', _data_uri(path))
        return tag

    page = _LINK_TAG_RE.sub(replace_link, page)

    def replace_script(match: re.Match[str]) -> str:
        tag = match[0]
        attrs = _tag_attributes(tag)
        src = attrs.get('src', '')
        path = _local_asset_path(src, page_dir, outdir)
        if path is None:
            return tag
        try:
            script = path.read_text(encoding='utf-8')
        except (OSError, UnicodeDecodeError):
            return tag
        # prevent the script content from terminating the element early;
        # within JavaScript string literals this is an escaped forward slash
        script = _SCRIPT_CLOSE_RE.sub(r'<\\/\1', script)
        remaining = _ATTR_RE.sub(
            lambda m: '' if m['name'].lower() == 'src' else m[0],
            match['attrs'],
        ).strip()
        remaining_attrs = f' {remaining}' if remaining else ''
        return f'<script{remaining_attrs}>{script}</script>'

    page = _SCRIPT_TAG_RE.sub(replace_script, page)

    def replace_img(match: re.Match[str]) -> str:
        tag = match[0]
        src = _tag_attributes(tag).get('src', '')
        path = _local_asset_path(src, page_dir, outdir)
        if path is None:
            return tag
        return _replace_attribute_value(tag, 'src', _data_uri(path))

    page = _IMG_TAG_RE.sub(replace_img, page)

    page_path.write_text(page, encoding='utf-8')


def _embed_assets(app: Sphinx, exc: Exception | None) -> None:
    """Embed local assets into the page written by the singlehtml builder."""
    builder = app.builder
    if exc is not None or not isinstance(builder, SingleFileHTMLBuilder):
        return
    if not app.config.singlehtml_embed_assets:
        return
    with progress_message(__('embedding assets')):
        page_path = builder.get_output_path(builder.config.root_doc)
        _embed_assets_in_page(page_path, Path(builder.outdir))


def setup(app: Sphinx) -> ExtensionMetadata:
    app.setup_extension('sphinx.builders.html')

    app.add_builder(SingleFileHTMLBuilder)
    app.add_config_value(
        'singlehtml_sidebars',
        lambda self: self.html_sidebars,
        'html',
        types=frozenset({dict}),
    )
    app.add_config_value(
        'singlehtml_embed_assets',
        False,
        'html',
        types=frozenset({bool}),
    )
    # run late (priority 999) so that assets copied by other extensions'
    # ``build-finished`` handlers are embedded as well
    app.connect('build-finished', _embed_assets, priority=999)

    return {
        'version': 'builtin',
        'parallel_read_safe': True,
        'parallel_write_safe': True,
    }
